# Generated by Django 5.0.1 on 2024-01-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventReadyAPI", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketingposter",
            name="id",
            field=models.IntegerField(
                editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="marketingposter",
            name="image",
            field=models.ImageField(upload_to="files/posters"),
        ),
    ]
