# Generated by Django 5.0.1 on 2024-01-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventReadyAPI", "0002_alter_marketingposter_id_alter_marketingposter_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketingposter",
            name="image",
            field=models.ImageField(upload_to="../../eventready/src/files/posters"),
        ),
    ]
