# Generated by Django 5.0.1 on 2024-01-21 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eventReadyAPI", "0003_alter_project_id"),
    ]

    operations = [
        migrations.RenameModel(old_name="Project", new_name="EventGeneralInfo",),
    ]
