# Generated by Django 5.0.1 on 2024-02-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventReadyAPI", "0009_alter_marketingposter_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketingRecapPhotos",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Name")),
                ("image", models.ImageField(upload_to="images/recap")),
            ],
        ),
        migrations.CreateModel(
            name="MarketingReminders",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Name")),
                ("time", models.TimeField(verbose_name="Date Time")),
            ],
        ),
    ]
