# Generated by Django 4.2.10 on 2024-02-22 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("eventReadyAPI", "0011_marketingreminders_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketingposter",
            name="event",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marketingPosters",
                to="eventReadyAPI.eventgeneralinfo",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="marketingrecapphotos",
            name="event",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marketingRecapPhotos",
                to="eventReadyAPI.eventgeneralinfo",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="marketingreminders",
            name="event",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marketingReminders",
                to="eventReadyAPI.eventgeneralinfo",
            ),
            preserve_default=False,
        ),
    ]
