# Generated by Django 5.0.1 on 2024-02-25 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventReadyAPI', '0009_alter_task_priority_alter_task_status'),
        ('eventReadyAPI', '0013_rename_event_marketingposter_event_id_and_more'),
    ]

    operations = [
    ]
