# Generated by Django 4.2.10 on 2024-03-11 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("eventReadyAPI", "0019_task_goal"),
    ]

    operations = [
        migrations.AddField(
            model_name="goals",
            name="tasks",
            field=models.ManyToManyField(
                blank=True, related_name="goals", to="eventReadyAPI.task"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="goal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks_to_goal",
                to="eventReadyAPI.goals",
            ),
        ),
    ]
