# Generated by Django 4.2.10 on 2024-03-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventReadyAPI", "0021_alter_goals_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goals",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
