# Generated by Django 4.2.10 on 2024-03-12 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventReadyAPI", "0022_alter_goals_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketingposter",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="marketingrecapphotos",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="marketingreminders",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
