# Generated by Django 4.2.10 on 2024-03-16 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("eventReadyAPI", "0024_alter_goals_name_budgetitem_budgetcategory_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="budget_category",
                to="eventReadyAPI.budgetcategory",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="items",
            field=models.ManyToManyField(
                blank=True, related_name="budget_item", to="eventReadyAPI.budgetitem"
            ),
        ),
        migrations.AddField(
            model_name="budgetcategory",
            name="budget",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categories_related",
                to="eventReadyAPI.budget",
            ),
        ),
        migrations.AddField(
            model_name="budgetcategory",
            name="items",
            field=models.ManyToManyField(
                blank=True, related_name="category_item", to="eventReadyAPI.budgetitem"
            ),
        ),
        migrations.AddField(
            model_name="budgetitem",
            name="budget",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items_related",
                to="eventReadyAPI.budget",
            ),
        ),
        migrations.AddField(
            model_name="budgetitem",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items_related",
                to="eventReadyAPI.budgetcategory",
            ),
        ),
        migrations.AlterField(
            model_name="budgetcategory",
            name="event_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budget_categories",
                to="eventReadyAPI.eventgeneralinfo",
            ),
        ),
        migrations.AlterField(
            model_name="budgetitem",
            name="event_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budget_items",
                to="eventReadyAPI.eventgeneralinfo",
            ),
        ),
    ]
