# Generated by Django 5.0.1 on 2024-03-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventReadyAPI', '0026_budget_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgeneralinfo',
            name='user',
            field=models.CharField(default='user_2dkFQzcVpWIx6zYlWdeJxIRzuZs', editable=False, max_length=255),
            preserve_default=False,
        ),
    ]
