# Generated by Django 4.2.4 on 2024-04-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventReadyAPI', '0027_eventgeneralinfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventgeneralinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='eventgeneralinfo',
            name='user_id',
            field=models.CharField(default='user_2dkFQzcVpWIx6zYlWdeJxIRzuZs',null=False, editable=False, max_length=255),
            preserve_default=False,
        ),
    ]
