# Generated by Django 5.0.1 on 2024-03-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventReadyAPI', '0027_attendee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
