# Generated by Django 4.2.4 on 2024-04-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventReadyAPI', '0028_remove_eventgeneralinfo_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgeneralinfo',
            name='user_id',
            field=models.CharField(default='user_2dkFQzcVpWIx6zYlWdeJxIRzuZs', editable=False, max_length=255),
        ),
    ]
