# Generated by Django 4.2.4 on 2024-04-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventReadyAPI', '0029_alter_eventgeneralinfo_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgeneralinfo',
            name='user_id',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
