# Generated by Django 5.0.1 on 2024-03-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventReadyAPI', '0029_alter_attendee_email_alter_attendee_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
