# Generated by Django 4.2.10 on 2024-03-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventReadyAPI", "0030_alter_attendee_email"),
    ]

    operations = [
        migrations.RemoveField(model_name="budget", name="leftover",),
        migrations.RemoveField(model_name="budget", name="name",),
        migrations.RemoveField(model_name="budget", name="progress",),
        migrations.RemoveField(model_name="budget", name="total",),
        migrations.RemoveField(model_name="budgetcategory", name="total",),
        migrations.AddField(
            model_name="budgetitem",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="budget_attachments/",
                verbose_name="Attachment",
            ),
        ),
        migrations.AlterField(
            model_name="budgetitem",
            name="total",
            field=models.FloatField(default=0, verbose_name="Total"),
            preserve_default=False,
        ),
    ]
