# Generated by Django 5.0.1 on 2024-03-27 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventReadyAPI', '0031_remove_budget_categories_remove_budget_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='progress',
        ),
    ]
