# Generated by Django 5.0.1 on 2024-03-25 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventReadyAPI', '0032_rename_budget_budgetcategory_budget_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetcategory',
            old_name='budget_id',
            new_name='budget',
        ),
        migrations.RenameField(
            model_name='budgetitem',
            old_name='category_id',
            new_name='category',
        ),
    ]
