# Generated by Django 4.2.4 on 2024-04-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventReadyAPI', '0032_remove_budget_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgeneralinfo',
            name='user_id',
            field=models.CharField(default='user_2dkFQzcVpWIx6zYlWdeJxIRzuZs', max_length=255),
        ),
    ]
