# Generated by Django 4.2.10 on 2024-03-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventReadyAPI", "0032_rename_budget_budgetcategory_budget_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="name",
            field=models.CharField(
                default="Worldwide 2024 Budget", max_length=64, verbose_name="Name"
            ),
            preserve_default=False,
        ),
    ]
