# Generated by Django 5.0.1 on 2024-03-27 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventReadyAPI', '0031_remove_budget_categories_remove_budget_items_and_more'),
        ('eventReadyAPI', '0033_budget_name'),
        ('eventReadyAPI', '0033_rename_budget_id_budgetcategory_budget_and_more'),
    ]

    operations = [
    ]
