# Generated by Django 5.0.1 on 2024-02-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventReadyAPI", "0007_marketingposter"),
    ]

    operations = [
        migrations.RemoveField(model_name="marketingposter", name="description",),
        migrations.AddField(
            model_name="marketingposter",
            name="caption",
            field=models.CharField(
                blank=True, max_length=1024, null=True, verbose_name="Caption"
            ),
        ),
        migrations.AlterField(
            model_name="marketingposter",
            name="name",
            field=models.CharField(max_length=256, verbose_name="Name"),
        ),
    ]
