# Generated by Django 5.0.1 on 2024-02-25 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventReadyAPI', '0007_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='event',
            new_name='event_id',
        ),
    ]
