# Generated by Django 5.0.1 on 2024-02-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventReadyAPI", "0008_remove_marketingposter_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketingposter",
            name="id",
            field=models.IntegerField(
                editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
