# Generated by Django 5.0.1 on 2024-02-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventReadyAPI", "0010_marketingrecapphotos_marketingreminders"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketingreminders",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="marketingreminders",
            name="time",
            field=models.TimeField(blank=True, null=True, verbose_name="Time"),
        ),
    ]
