# Generated by Django 4.2.10 on 2024-02-25 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eventReadyAPI", "0014_goals"),
        ("eventReadyAPI", "0014_merge_20240225_1727"),
    ]

    operations = []
