# Generated by Django 4.2.10 on 2024-03-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "eventReadyAPI",
            "0025_budget_categories_budget_items_budgetcategory_budget_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="name",
            field=models.CharField(
                default="budget", max_length=64, verbose_name="Name"
            ),
            preserve_default=False,
        ),
    ]
