# Generated by Django 5.0.1 on 2024-03-27 01:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventReadyAPI', '0030_alter_attendee_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='items',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='name',
        ),
    
        migrations.RemoveField(
            model_name='budgetcategory',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='budgetcategory',
            name='items',
        ),
        migrations.RemoveField(
            model_name='budgetitem',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='budgetitem',
            name='event_id',
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='budget_attachments/', verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='leftover',
            field=models.FloatField(default=0.0, verbose_name='Leftover'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='total',
            field=models.FloatField(default=0.0, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='budgetcategory',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='eventReadyAPI.budget'),
        ),
        migrations.AlterField(
            model_name='budgetcategory',
            name='total',
            field=models.FloatField(default=0.0, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='eventReadyAPI.budgetcategory'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='cost',
            field=models.FloatField(default=0.0, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='total',
            field=models.FloatField(default=0.0, verbose_name='Total'),
        ),
    ]
